CREATE DATABASE gestion_etudiant 
DEFAULT CHARACTER SET utf8mb4 
DEFAULT COLLATE utf8mb4_uniquecode_ci;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE etudiants (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    telephone INT NOT NULL UNIQUE,
    sexe VARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE
);